name: TWS CD Workflow

on: 
    workflow_run:
        workflows: ["TWS CI Workflow"] 
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # this happens in the runner

            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                    name: TWS CD Workflow

on: 
    workflow_run:
        workflows: ["TWS CI Workflow"] 
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # this happens in the runner

            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                    https://github.com/ojaslan/githubactions-demo.git
                    cd ~/githubactions-demo
                    git pull origin main
                    docker compose pull
                    docker compose down && docker compose up -d
                    cd ~/github-actions-demo
                    git pull origin main
                    docker compose pull
                    docker compose down && docker compose up -d
